services:
  - type: web
    name: coformacion-backend
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend_uniempresarial.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: coformacion-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://coformacion-frontend.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://coformacion-backend.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL_REQUIRED
        value: "True"


